services:
  magnolia:
    image: formentor/magnolia-cms
    build: ./magnolia-cms
    volumes:
      - magnolia-data:/opt/magnolia/data
    ports:
      - "8080:8080"
    environment:
      - MGNL_GITHUB_TOKEN=ghp
      - MGNL_GITHUB_REPO=astro-with-magnolia
      - MGNL_GITHUB_REPO_OWNER=formentor-studio
volumes:
  magnolia-data: 
